return {
 	--"neovim/nvim-lspconfig",
-- 	config = function()
-- 		-- Keymaps
-- 		vim.api.nvim_create_autocmd("LspAttach", {
-- 			group = vim.api.nvim_create_augroup("UserLspConfig", {}),
-- 			callback = function(ev)
-- 
-- 				local map = vim.keymap.set
-- 				local opts = { buffer = ev.buf, silent = true }
-- 
-- 				-- Josean Martinez recs:
-- 				opts.desc = "Show LSP references (Telescope)"
-- 				map("n", "gR", "<cmd>Telescope lsp_references<CR>", opts)
-- 
-- 				opts.desc = "Go to declaration"
-- 				map("n", "gD", vim.lsp.buf.declaration, opts)
-- 
-- 				opts.desc = "Show LSP definition"
-- 				map("n", "gd", vim.lsp.buf.definition, opts)
-- 
-- 				opts.desc = "Show LSP implementations"
-- 				map("n", "gi", "<cmd>Telescope lsp_implementations<CR>", opts)
-- 
-- 				opts.desc = "Show LSP type definitions"
-- 				map("n", "gt", "<cmd>Telescope lsp_type_definitions<CR>", opts) -- show lsp type definitions
-- 
-- 				opts.desc = "See available code actions"
-- 				map({ "n", "v" }, "<leader>ca", vim.lsp.buf.code_action, opts) -- see available code actions, in visual mode will apply to selection
-- 
-- 				opts.desc = "Smart rename"
-- 				map("n", "<leader>rn", vim.lsp.buf.rename, opts) -- smart rename
-- 
-- 				opts.desc = "Show buffer diagnostics"
-- 				map("n", "<leader>D", "<cmd>Telescope diagnostics bufnr=0<CR>", opts) -- show  diagnostics for file
-- 
-- 				opts.desc = "Show line diagnostics"
-- 				map("n", "<leader>d", vim.diagnostic.open_float, opts) -- show diagnostics for line
-- 
-- 				opts.desc = "Go to previous diagnostic"
-- 				map("n", "[d", function()
-- 				  vim.diagnostic.jump({ count = -1, float = true })
-- 				end, opts) -- jump to previous diagnostic in buffer
-- 				--
-- 				opts.desc = "Go to next diagnostic"
-- 				map("n", "]d", function()
-- 				  vim.diagnostic.jump({ count = 1, float = true })
-- 				end, opts) -- jump to next diagnostic in buffer
-- 
-- 				opts.desc = "Show documentation for what is under cursor"
-- 				map("n", "K", vim.lsp.buf.hover, opts) -- show documentation for what is under cursor
-- 
-- 				opts.desc = "Restart LSP"
-- 				map("n", "<leader>rs", ":LspRestart<CR>", opts) -- mapping to restart lsp if necessary
-- 
-- 			end,
-- 		})
-- 	end,
}
