return {
-- 	{
-- 		"mason-org/mason.nvim",
-- 		opts = {
-- 			ui = {
-- 			icons = {
-- 				package_installed = "✓",
-- 				package_pending = "➜",
-- 				package_uninstalled = "✗"
-- 			}},
-- 		},
-- 	},
-- 	{
-- 		"mason-org/mason-lspconfig.nvim",
-- 		dependencies = { "mason-org/mason.nvim", "neovim/nvim-lspconfig" },
-- 		opts = {
-- 			ensure_installed = {
-- 				"clangd",
-- 				"basedpyright",
-- 				"lua_ls"
-- 			},
-- 			automatic_enable = true,
-- 		},
-- 	},
}
