
# === BASIC SETTINGS ===

# Set second prefix for better ergonomics
set -g prefix2 C-s
bind C-s send-prefix

# Colors
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm-kitty:RGB"

# Eliminate delay after pressing Escape
set -sg escape-time 0

# Time (ms) allowed for repeatable key presses 
set -g repeat-time 500

# Increase scrollback buffer
set -g history-limit 50000

# Enable mouse support
set -g mouse on

# Start windows and panes at 1 instead of 0
set -g base-index 1
setw -g pane-base-index 1

# Renumber windows automatically
set -g renumber-windows on

# Enable focus events for vim autoread
set -g focus-events on


# === APPEARANCE ===

# Status bar position
set -g status-position top

# Status bar length
set -g status-left-length 200
set -g status-right-length 200

# Status bar content
set -g status-left '[#S] '
set -g status-right '"#T" %H:%M %d-%b-%y '
setw -g window-status-format '#I:#W#F'
setw -g window-status-current-format '#[bold]#I:#W#F'

# Set terminal window/tab title 
set -g set-titles on
set -g set-titles-string "tmux/#S"


# === KEYBINDS ===

# Reload config
bind r source-file ~/.tmux.conf \; display "Reloaded configuration!"

# Navigation
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# Vi copy mode
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel \
  'if [ -n "$WAYLAND_DISPLAY" ]; then wl-copy; else xclip -in -selection clipboard; fi'
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel \
  'if [ -n "$WAYLAND_DISPLAY" ]; then wl-copy; else xclip -in -selection clipboard; fi'

# Tmux sessionizer
bind -r f neww '$SCRIPTS/tmux-sessionizer'
set -g update-environment "PROJECT"
bind -r P run-shell '~/.local/bin/tmux-sessionizer $PROJECT'


# === LOCAL CONFIG =====================================================

# Source local configuration if it exists
if-shell "[ -f ~/.tmux.conf.local ]" "source-file ~/.tmux.conf.local"
