
# === LOOKS ============================================================

# BEGIN_KITTY_THEME
include current-theme.conf
# END_KITTY_THEME

# Transparency
background_opacity 0.90

hide_window_decorations yes

tab_bar_style powerline

# # Minimum number of tabs to enable tab bar
# tab_bar_min_tabs 1					

cursor_trail 1


# === BEHAVIOR ==========================================================

# Bell
enable_audio_bell no

# Scrollback (default = 2000)
scrollback_lines 10000

# Open new OS windows in current working directory
map ctrl+shift+n new_os_window_with_cwd

# Open new tabs in current working directory
map Ctrl+Shift+t new_tab_with_cwd	

# Open new windows in current working directory
map ctrl+shift+enter new_window_with_cwd


# === KEYMAPS ==========================================================

# # Window multiplexing
# map ctrl+shift+h neighboring_window left
# map ctrl+shift+j neighboring_window down
# map ctrl+shift+k neighboring_window up
# map ctrl+shift+l neighboring_window right


# === LOCAL CONFIG ======================================================

include local.conf
